{% set name = "openmc-plotter" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openmc-plotter-{{ version }}.tar.gz
  sha256: ebe38764e4b6c973765162e8d6f0f036764b5231beb21e084e77888392cfe4ee
build:
  entry_points:
    - openmc-plotter=openmc_plotter.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - openmc >0.12.2
    - pyside6
    - python >={{ python_min }}

test:
  imports:
    - openmc_plotter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/openmc-dev/plotter
  summary: Plotting tool for OpenMC models and tally data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kkiesling
    - paulromano
    - pshriwise
