{% set name = "openmc-plotter" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmc-plotter-{{ version }}.tar.gz
  sha256: 22a1d954bd91a84ed282282cbec7e1d88f70876bfe0afde90a765a1668a5b3a8
build:
  entry_points:
    - openmc-plotter=openmc_plotter.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python  >=3.6
  run:
    - matplotlib-base
    - numpy
    - openmc >0.12.2
    - pyside2
    - python  >=3.6

test:
  imports:
    - openmc_plotter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openmc-dev/plotter
  summary: Plotting tool for OpenMC models and tally data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kkiesling
    - paulromano
    - pshriwise
